### PR TITLE
Add CI/CD anomaly detection demo notebook and utils

### LINKED ISSUE #2: Add anomaly detection notebook
**Is your feature request related to a problem? Please describe.**
No anomaly detection notebooks in this repo yet.

**Describe the solution you'd like**
The internal version of this repo contains the anomaly detection demo notebook. Ensure that all customer sensitive data is removed (if it exists) from it and make it available here.

### PR DESCRIPTION
**Pull request by chauhankaranraj**
## Related Issues and Dependencies

Fixes #2 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

See below

## Description

The anomaly detection demo notebook (only CI/CD data) in this PR is almost same as the internal notebook. The main differences are as follows
- remove query that identifies ci/cd deployments internally at Red Hat, for privacy reasons
- update cache dir, since this notebook has been moved to `stage` dir
- update markdown

The `utils.py` is almost the same as `prom_query.py` used internally. Only difference is that results are stored as parquet instead of pickle format.

The `evaluate.py` is a subset of `utils.py` used internally, containing only the functions relevant for anomaly detection.

Updated pipfile, pipfile.lock

### CODE REVIEW

**Comment by chauhankaranraj** [comment]
@goern hey Christoph it seems like I am unable to run retest on this PR. Any ideas how to proceed?

**Comment by harshad16** [comment]
@chauhankaranraj can you try again once more.

**Comment by harshad16** [comment]
there is network issue on the ci cluster, pods are unable to init, have opened issue with infra team.

**Review by MichaelClifford — CHANGES_REQUESTED** [review]
:+1: couple minor changes in the notebook

**Review by MichaelClifford — APPROVED** [review]
:+1:  squash commits please

**Comment by chauhankaranraj** [comment]
>  squash commits please

thanks for the feedback, commits squashed :)

**Pull request merged**
